import os, io, json
from pptx import Presentation
from pptx.util import Inches, Pt
from reportlab.pdfgen import canvas

def make_pptx(slides, out_path: str, title: str = "TaoWorks AI"):
    prs = Presentation()
    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by TaoWorks AI"

    # Content slides
    content_layout = prs.slide_layouts[1]
    for s in slides:
        sl = prs.slides.add_slide(content_layout)
        sl.shapes.title.text = s.get("title", "")
        body = sl.placeholders[1].text_frame
        body.clear()
        for b in s.get("bullets", [])[:5]:
            p = body.add_paragraph()
            p.text = b
            p.level = 0
    prs.save(out_path)
    return out_path

def make_pdf_from_outline(slides, out_path: str, title: str):
    c = canvas.Canvas(out_path)
    textobject = c.beginText(40, 800)
    textobject.setFont("Helvetica", 14)
    textobject.textLine(title)
    textobject.textLine("")
    for idx, s in enumerate(slides, 1):
        textobject.textLine(f"Slide {idx}: {s.get('title','')}")
        for b in s.get("bullets", []):
            textobject.textLine(f"  • {b}")
        textobject.textLine("")
    c.drawText(textobject)
    c.showPage()
    c.save()
    return out_path
